# Generated by Django 5.0.1 on 2024-03-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('birth_certificate_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('register_by', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('home_add', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChildVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_1month', models.CharField(max_length=30)),
                ('vaccination_2month', models.CharField(max_length=30)),
                ('vaccination_3month', models.CharField(max_length=30)),
                ('vaccination_6month', models.CharField(max_length=30)),
                ('vaccination_7month', models.CharField(max_length=30)),
                ('vaccination_8month', models.CharField(max_length=30)),
                ('vaccination_9month', models.CharField(max_length=30)),
                ('vaccination_12month', models.CharField(max_length=30)),
                ('vaccination_15month', models.CharField(max_length=30)),
                ('vaccination_18month', models.CharField(max_length=30)),
                ('vaccination_24month', models.CharField(max_length=30)),
                ('vaccination_36month', models.CharField(max_length=30)),
                ('vaccination_48month', models.CharField(max_length=30)),
                ('vaccination_60month', models.CharField(max_length=30)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRIMARY_HEALTH_CENTER.child')),
            ],
        ),
    ]
