# Generated by Django 5.0.1 on 2024-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0006_child_childvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(default='m', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(max_length=100),
        ),
    ]
