# Generated by Django 5.0.1 on 2024-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0009_alter_admin_email_alter_child_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvaccination',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
