# Generated by Django 5.0.1 on 2024-03-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0011_alter_childvaccination_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birth_certificate_id',
            new_name='child_id',
        ),
    ]
