# Generated by Django 5.0.1 on 2024-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0012_rename_birth_certificate_id_child_child_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email_verify',
            field=models.CharField(default='unverified', max_length=10),
        ),
        migrations.AddField(
            model_name='admin',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='child',
            name='email_verify',
            field=models.CharField(default='unverified', max_length=10),
        ),
        migrations.AddField(
            model_name='child',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='users',
            name='email_verify',
            field=models.CharField(default='unverified', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
