# Generated by Django 5.0.1 on 2024-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0013_admin_email_verify_admin_otp_child_email_verify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
