# Generated by Django 5.0.1 on 2024-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0014_alter_admin_otp_alter_child_otp_alter_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_12month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_15month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_18month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_1month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_24month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_2month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_36month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_3month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_48month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_60month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_6month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_7month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_8month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccination',
            name='vaccination_9month',
            field=models.CharField(max_length=50),
        ),
    ]
