# Generated by Django 5.0.1 on 2024-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMARY_HEALTH_CENTER', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='mobile_no',
            new_name='contact_no',
        ),
    ]
